export const reviews = [
  {
    id: 1,
    title: 'Fast and Easy',
    img: '/assets/img/car1.png',
    content: 'Quick booking and great vehicle options. Made my trip stress-free!',
    score: 5,
  },
  {
    id: 2,
    title: 'Seamless Experience',
    img: '/assets/img/car2.png',
    content: 'Easy to book, clear pricing, and no hidden fees. Highly recommend!',
    score: 5,
  },
  {
    id: 3,
    title: 'Perfect for My Trip',
    img: '/assets/img/car3.png',
    content: 'The car was in perfect condition, and process was smooth',
    score: 4,
  },
  {
    id: 4,
    title: 'Highly Reliable',
    img: '/assets/img/car4.png',
    content: 'Never had an issue. Always on time and great service.',
    score: 5,
  },
  {
    id: 5,
    title: 'Smooth Booking Process',
    img: '/assets/img/car5.png',
    content: 'Quick, simple, and hassle-free. Couldn’t be easier',
    score: 5,
  },
  {
    id: 6,
    title: 'Highly Recommended!',
    img: '/assets/img/car6.png',
    content: 'Efficient service and top-notch vehicles. I’ll be back for sure!',
    score: 3,
  },
  {
    id: 7,
    title: 'Stress-Free Booking',
    img: '/assets/img/car1.png',
    content: 'Booking was smooth, and the car was perfect for my needs.',
    score: 5,
  },
  {
    id: 8,
    title: 'Great Value',
    img: '/assets/img/car5.png',
    content: 'Affordable pricing and a smooth process. Definitely worth it!',
    score: 5,
  },
]